import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import MainWrapper from '../components/layout/MainWrapper';
import Provider from '@/app/Provider';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Aidol',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Provider>
          <Header />
          <MainWrapper>{children}</MainWrapper>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
